server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: gateway-microservice
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: clients
              uri: http://client-microservice:8081
              predicates:
                - Path=/api/v2/clients/**

            - id: instructors
              uri: http://instructor-microservice:8084
              predicates:
                - Path=/api/v2/instructors/**

            - id: courses
              uri: http://course-microservice:8082
              predicates:
                - Path=/api/v2/courses/**

            - id: inscriptions
              uri: http://inscription-microservice:8083
              predicates:
                - Path=/api/v2/inscription/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka