CREATE TABLE CATEGORY (
    ID_CATEGORY INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    NAME_CATEGORY VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE COURSE (
    ID_COURSE INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME_COURSE VARCHAR(255) NOT NULL,
    DESCRIPTION_COURSE TEXT,
    ID_INSTRUCTOR INTEGER NOT NULL,
    ID_CATEGORY INTEGER NOT NULL,
    CONSTRAINT fk_course_category FOREIGN KEY (id_category)
            REFERENCES CATEGORY(id_category)
            ON DELETE RESTRICT
            ON UPDATE CASCADE
);