INSERT INTO COURSE (NAME, DESCRIPTION_COURSE, ID_INSTRUCTOR) VALUES
('Desarrollo Frontend con React', 'Creación de interfaces de usuario modernas y responsivas', 1), -- María González (Programación Web)
('Fundamentos de HTML y CSS', 'Bases del desarrollo web frontend', 1), -- María González (Programación Web)
('Bases de Datos Relacionales', 'Diseño y gestión de bases de datos SQL', 2), -- Carlos Rodríguez (Base de Datos)
('Optimización de Consultas SQL', 'Técnicas avanzadas para mejorar el rendimiento de BD', 2), -- Carlos Rodríguez (Base de Datos)
('Desarrollo de Apps Android', 'Creación de aplicaciones móviles nativas para Android', 3), -- Ana López (Desarrollo Mobile)
('Flutter para Multiplataforma', 'Desarrollo de apps móviles con Flutter', 3), -- Ana López (Desarrollo Mobile)
('Introducción al Machine Learning', 'Fundamentos de aprendizaje automático con Python', 4), -- Pedro Martínez (Machine Learning)
('Deep Learning con TensorFlow', 'Redes neuronales profundas para IA', 4), -- Pedro Martínez (Machine Learning)
('Seguridad en Aplicaciones Web', 'Técnicas de protección contra vulnerabilidades', 5), -- Laura Sánchez (Ciberseguridad)
('Ethical Hacking', 'Pruebas de penetración y auditorías de seguridad', 5), -- Laura Sánchez (Ciberseguridad)
('Docker y Containerización', 'Despliegue de aplicaciones con contenedores', 6), -- Diego Torres (DevOps)
('CI/CD con Jenkins', 'Integración y despliegue continuo automatizado', 6), -- Diego Torres (DevOps)
('Diseño de Experiencia de Usuario', 'Principios y metodologías de UX Design', 7), -- Sofía Herrera (UX/UI Design)
('Prototipado con Figma', 'Herramientas de diseño para interfaces digitales', 7), -- Sofía Herrera (UX/UI Design)
('AWS Cloud Fundamentals', 'Servicios básicos de Amazon Web Services', 8), -- Roberto Silva (Cloud Computing)
('Kubernetes en la Nube', 'Orquestación de contenedores en cloud', 8), -- Roberto Silva (Cloud Computing)
('Análisis de Datos con Python', 'Procesamiento y visualización de datos', 9), -- Carmen Ruiz (Análisis de Datos)
('Business Intelligence', 'Herramientas de inteligencia de negocios', 9), -- Carmen Ruiz (Análisis de Datos)
('Patrones de Diseño de Software', 'Arquitecturas escalables y mantenibles', 10), -- Andrés Morales (Arquitectura de Software)
('Microservicios y APIs', 'Diseño de sistemas distribuidos modernos', 10); -- Andrés Morales (Arquitectura de Software)